//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created on ___DATE___.
//___COPYRIGHT___
//___COREDATAFILECOMMENTEPILOGUE___

#import "___COREDATA_DATAMODELNAME___+CoreDataModel.h"

___COREDATA_DATAMODEL_MANAGEDOBJECTCLASSES_IMPLEMENTATIONS___
