//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created on ___DATE___.
//___COPYRIGHT___
//___COREDATAFILECOMMENTEPILOGUE___

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

___COREDATA_DATAMODEL_MANAGEDOBJECTCLASSES_IMPORTS___

___COREDATA_DATAMODEL_MANAGEDOBJECTCLASSES_REFERENCES___

___COREDATA_DATAMODEL_MANAGEDOBJECTCLASSES_INTERFACES___
