//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created on ___DATE___.
//___COPYRIGHT___
//___COREDATAFILECOMMENTEPILOGUE___

___COREDATAMANAGEDOBJECTCLASSIMPORT___

NS_ASSUME_NONNULL_BEGIN

@interface ___FILEBASENAMEASIDENTIFIER___ (CoreDataProperties)

___COREDATAPROPERTYDECLARATIONS___
@end

NS_ASSUME_NONNULL_END
