//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created on ___DATE___.
//___COPYRIGHT___
//___COREDATAFILECOMMENTEPILOGUE___

#import <Foundation/Foundation.h>
___COREDATAMANAGEDOBJECTSUPERCLASSIMPORT______COREDATAMANAGEDOBJECTCLASSREFERENCES___
NS_ASSUME_NONNULL_BEGIN

@interface ___FILEBASENAMEASIDENTIFIER___ : ___COREDATAMANAGEDOBJECTSUPERCLASS___

@end

NS_ASSUME_NONNULL_END

#import "___FILEBASENAME___+CoreDataProperties.h"
