//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created on ___DATE___.
//___COPYRIGHT___
//___COREDATAFILECOMMENTEPILOGUE___

import Foundation
import CoreData
___COREDATAMANAGEDOBJECTIMPORTEDMODULES___

extension ___FILEBASENAMEASIDENTIFIER___ {

___COREDATAPROPERTYIMPLEMENTATIONS___
}
